### PR TITLE
Elastic 5.x

### PR DESCRIPTION
**Pull request by juju4**
add option for repo between elastic 2.x or 5.x - latest requires java8
travis test include only for xenial as only one with java8 in official distribution

### CODE REVIEW

**Comment by fago** [comment]
I also needed 5.x support. As the versions are quite different, I think it does not make much sense to support all of them in a single role. -> https://github.com/drunomics/ansible-role-elasticsearch

**Comment by juju4** [comment]
That's up to each person choice
but software release will make older releases deprecated so it's the natural way to move up
v1 is already EOL and v2.4 is maintained up to feb 2018
https://www.elastic.co/support/eol

For me, it makes sense to keep the 2 or 3 latest in the same role, still same software.

**Comment by fago** [comment]
Sure, no objections - it just becomes a bit harder and confusing to use when half of the settings only apply to a specific version.

**Comment by jamesgrobertson** [comment]
I applied this patch to the master branch, and, due to a bug in Ubuntu, composer doesn't work. I get a segmentation fault when I try to use it.

**Comment by joestewart** [comment]
Successful manual testing of 2.x, 5.x and ( correct) failure when changing versions from 2.x to 5.x.

.travis.yml conflict still outstanding.

**Comment by sfblaauw** [comment]
+1

**Comment by geerlingguy** [comment]
6.x is here... I'm going to work on making it configurable a little differently; also there are a number of other changes in this PR that I would rather have broken out and explained separately. As it is, this role's primary purpose is to get elasticsearch installed, and at least _lightly_ configured for many use cases.

**Pull request closed without merging**
